version: '3.8'
services:
  service1:
    build: ./service1
    container_name: service1
    restart: unless-stopped
    ports:
      - 9999:80
    depends_on:
      - service1-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword1
    networks:
      vpcbr1:
        ipv4_address: 10.5.0.2
      net1:
        ipv4_address: 20.20.0.2
      internet:
  service1-db:
    container_name: service1-db
    build: ./service1/db
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: unless-stopped
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword1
    networks:
      vpcbr1:
        ipv4_address: 10.5.0.3
        

  service2:
    container_name: service2
    build: ./service2
    restart: unless-stopped
    depends_on:
      - service2-db
    networks:
      vpcbr2:
        ipv4_address: 10.7.0.2
      net1:
        ipv4_address: 20.20.0.3
      net2:
        ipv4_address: 172.16.0.2

  service2-db:
    build: ./service2/db
    container_name: service2-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword2
    networks:
      vpcbr2:
        ipv4_address: 10.7.0.3

  service3:
    container_name: service3
    build: ./service3
    networks:
      net2:
        ipv4_address: 172.16.0.3

networks:
  net1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 20.20.0.0/16
          gateway: 20.20.0.1
    internal: true
  net2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1
    internal: true
  vpcbr1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
    internal: true
  vpcbr2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.7.0.0/16
          gateway: 10.7.0.1
    internal: true
  internet: {}