version: "3.9"
services:
  mineme:
    build: .
    restart: always
    ports:
      - "13337:25565"
    volumes:
      - ./appdata/banned-ips.json:/app/banned-ips.json
      - ./appdata/banned-players.json:/app/banned-players.json
